### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by jreesun** [jreesun/krux#48]

**Comment by AshleyFires** [comment]
Can you provide more information about this please?

**Comment by jreesun** [comment]
Sure! Krux now has limited unicode support (latin and extended latin characters with diacritics), so I'm asking for help with translating its UI to the various languages that can be rendered with those characters. I _think_ this would include Vietnamese?

To add a translation, all you need to do is create a new file in the `i18n/translations` directory named after the locale that corresponds to it (`vi-VN.json` in this case). In the file, you map the English versions of the phrases to their Vietnamese equivalents.

Does that answer your question?

**Comment by AshleyFires** [comment]
Not sure I can translate it 100% right but I think I can help you a little bit about this issue. Can I join this project with you? 👍

**Comment by jreesun** [comment]
Yep, just make a pull request with your changes and I'll look it over. Thanks!

**Comment by AshleyFires** [comment]
Thanks, I'll try my best!

**Comment by jreesun** [comment]
Resolved by #64
